CREATE TABLE keys_attributes_probability (
    attribute_id INT PRIMARY KEY,
    attribute_name VARCHAR(255),
    Chicken FLOAT DEFAULT 0,
    Pizza FLOAT DEFAULT 0,
    Burger FLOAT DEFAULT 0,
    Salad FLOAT DEFAULT 0,
    Pasta FLOAT DEFAULT 0,
    Sushi FLOAT DEFAULT 0,
    Steak FLOAT DEFAULT 0,
    Tacos FLOAT DEFAULT 0,
    Soup FLOAT DEFAULT 0,
    Sandwich FLOAT DEFAULT 0,
    Fries FLOAT DEFAULT 0,
    Hotdog FLOAT DEFAULT 0,
    Curry FLOAT DEFAULT 0,
    Rice FLOAT DEFAULT 0,
    Fish FLOAT DEFAULT 0,
    Cake FLOAT DEFAULT 0
);
INSERT INTO keys_attributes_probability (
    attribute_id,
    attribute_name,
    Chicken,
    Pizza,
    Burger,
    Salad,
    Pasta,
    Sushi,
    Steak,
    Tacos,
    Soup,
    Sandwich,
    Fries,
    Hotdog,
    Curry,
    Rice,
    Fish,
    Cake
)
SELECT 
    attribute_id,
    attribute_name,
    (Chicken / NULLIF(total, 0)) * 100 AS Chicken,
    (Pizza / NULLIF(total, 0)) * 100 AS Pizza,
    (Burger / NULLIF(total, 0)) * 100 AS Burger,
    (Salad / NULLIF(total, 0)) * 100 AS Salad,
    (Pasta / NULLIF(total, 0)) * 100 AS Pasta,
    (Sushi / NULLIF(total, 0)) * 100 AS Sushi,
    (Steak / NULLIF(total, 0)) * 100 AS Steak,
    (Tacos / NULLIF(total, 0)) * 100 AS Tacos,
    (Soup / NULLIF(total, 0)) * 100 AS Soup,
    (Sandwich / NULLIF(total, 0)) * 100 AS Sandwich,
    (Fries / NULLIF(total, 0)) * 100 AS Fries,
    (Hotdog / NULLIF(total, 0)) * 100 AS Hotdog,
    (Curry / NULLIF(total, 0)) * 100 AS Curry,
    (Rice / NULLIF(total, 0)) * 100 AS Rice,
    (Fish / NULLIF(total, 0)) * 100 AS Fish,
    (Cake / NULLIF(total, 0)) * 100 AS Cake
FROM (
    SELECT 
        attribute_id,
        attribute_name,
        Chicken,
        Pizza,
        Burger,
        Salad,
        Pasta,
        Sushi,
        Steak,
        Tacos,
        Soup,
        Sandwich,
        Fries,
        Hotdog,
        Curry,
        Rice,
        Fish,
        Cake,
        (Chicken + Pizza + Burger + Salad + Pasta + Sushi + Steak + Tacos + Soup + Sandwich + Fries + Hotdog + Curry + Rice + Fish + Cake) AS total
    FROM keys_attributes
) AS subquery;